ARG BALENA_MACHINE_NAME="%%BALENA_MACHINE_NAME%%"

FROM balenalib/${BALENA_MACHINE_NAME}-debian:buster
RUN install_packages mosquitto
COPY mosquitto.conf /etc/mosquitto.conf

ENTRYPOINT ["mosquitto", "-c", "/etc/mosquitto.conf"]

